# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55bdd0fb0d15b0eff36259d0d248e8ddeb4e4bfbec382858c786afea5c3af34bd1d366a7ecc4af843f44cc0918bd37683cc1aa1d810dda31cbce6decb03872d4

test:
  secret_key_base: 5be56f15d4116197bb4559f28a5431e338de7b18b2ad25df6be9a637fe21f19d787ddf3730fa20a46365a2c1ea20a3668752f2e1c8c88288c86c1be550cc5c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
